server:
  port: 9002


spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #换成nginx做的1111集群
        server-addr: 192.168.0.102:1111

management:
  endpoints:
    web:
      exposure:
        exclude: '*'
